# Generated by Django 4.2.7 on 2023-11-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_complete_order_customer_alter_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
